#!/bin/bash
docker build \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --build-arg SENTRY_AUTH_TOKEN \
    --build-arg SENTRY_DSN=https://7a3ddfbacc0c4e2d98f105aa0f184e0b@sentry.io/1209883 \
    --build-arg SENTRY_RELEASE=$SOURCE_COMMIT \
    --build-arg LOCAL_API_URL=http://api:9000/ \
    --build-arg REMOTE_API_URL=https://api.noiseblend.com/ \
    --build-arg LOCAL_WS_URL=ws://api:9000 \
    --build-arg REMOTE_WS_URL=wss://api.noiseblend.com \
    --build-arg DOMAIN=www.noiseblend.com \
    --cache-from $DOCKER_REPO:latest \
    -f $DOCKERFILE_PATH -t $IMAGE_NAME .